In [5]:
import csv
f=open('seoul.csv')
data=csv.reader(f)
header=next(data)
max_tempdif=-999
max_temp=-999
min_temp=999
max_datedif=''
max_date=''
min_date=''
for row in data:
    if row[-1]==''or row[-2]=='':
        row[-1]=-999
        row[-2]=-999
        
    row[-1]=float(row[-1])
    row[-2]=float(row[-2])
    if max_tempdif<(row[4]-row[3]):
        max_datedif=row[0]
        max_tempdif=row[4]-row[3]
    if max_temp<row[4]:
        max_date=row[0]
        max_temp=row[4]
    if row[-1]==-999 or row[-2]==-999:
        row[-1]=100
        row[-2]=100
    if min_temp>row[3]:
        min_date=row[0]
        min_temp=row[3]
f.close()
print('근 한달 서울의 일교차가 가장 큰 날은',max_datedif+'로, 일교차는',max_tempdif,'도 였습니다.')
print('근 한달 서울의 최저기온이 가장 낮은 날은',min_date+'로,',min_temp,'도 였습니다.')
print('근 한달 서울의 최고기온이 가장 높은 날은',max_date+'로,',max_temp,'도 였습니다.')

근 한달 서울의 일교차가 가장 큰 날은 2021-04-21로, 일교차는 17.9 도 였습니다.
근 한달 서울의 최저기온이 가장 낮은 날은 2021-05-02로, 7.3 도 였습니다.
근 한달 서울의 최고기온이 가장 높은 날은 2021-05-14로, 30.8 도 였습니다.

In [15]:
import csv
f= open('subway.csv','rt',encoding='UTF-8')
data=csv.reader(f)
next(data)
st_num=0
nd_num=0
rd_num=0
st_name=''
nd_name=''
rd_name=''
re1st_num=10000000
re2nd_num=10000000
re3rd_num=10000000
re1st_name=''
re2nd_name=''
re3rd_name=''
print('-----------------------------------')
print('1.1호선')
print('2.2호선')
print('3.3호선')
print('4,4호선')
print('5.경부선')
print('6.경인선')
print('7.경원선')
print('8.안산선')
print('9.과천선')
print('10.분당선')
print('11.경부선')
print('12.일산선')
print('13.중앙선')
print('14.장항선')
print('15.경의선')
print('16.경춘선')
print('17.수인선')
print('18.경강선')
print('19.5호선')
print('20.6호선')
print('21.7호선')
print('22.8호선')
print('23.9호선')
print('24.공항철도1호선')
print('25.9호선 2~3단계')
print('26.우이신설선')
print('-----------------------------------')
h=int(input('이용객 순위를 볼 노선을 선택하십시오: '))
if(h==1):
    subway='1호선'
elif(h==2):
    subway='2호선'
elif(h==3):
    subway='3호선'
elif(h==4):
    subway='4호선'
elif(h==5):
    subway='경부선'
elif(h==6):
    subway='경인선'
elif(h==7):
    subway='경원선'
elif(h==8):
    subway='안산선'
elif(h==9):
    subway='과천선'
elif(h==10):
    subway='분당선'
elif(h==11):
    subway='경부선'
elif(h==12):
    subway='일산선'
elif(h==13):
    subway='중앙선'
elif(h==14):
    subway='장항선'
elif(h==15):
    subway='경의선'
elif(h==16):
    subway='경춘선'
elif(h==17):
    subway='수인선'
elif(h==18):
    subway='경강선'
elif(h==19):
    subway='5호선'
elif(h==20):
    subway='6호선'
elif(h==21):
    subway='7호선'
elif(h==22):
    subway='8호선'
elif(h==23):
    subway='9호선'
elif(h==24):
    subway='공항철도1호선'
elif(h==25):
    subway='9호선2~3단계'
elif(h==26):
    subway='우이신설선'

for row in data:
    row[4]=row[4].replace(',','')
    row[5]=row[5].replace(',','')
    row[4]=row[4].replace('-','0')
    row[5]=row[5].replace('-','0')
    row[5]=int(row[5])
    row[4]=int(row[4])
    if row[1]==subway:
        
        if rd_num<row[4]+row[5]:#3순위정하기
            rd_num=row[4]+row[5]
            rd_name=row[3]
        if rd_num>nd_num:#2순위정하기
            temp=nd_num
            tempname=nd_name
            nd_num=rd_num
            nd_name=rd_name
            rd_num=temp
            rd_name=tempname
        if nd_num>st_num:#1순위정하기
            temp=st_num
            tempname=st_name
            st_num=nd_num
            st_name=nd_name
            nd_num=temp
            nd_name=tempname
        if re3rd_num>row[4]+row[5]:#적은3순위
            re3rd_num=row[4]+row[5]
            re3rd_name=row[3]
        if re3rd_num<re2nd_num:#적은2순위
            temp=re2nd_num
            tempname=re2nd_name
            re2nd_num=re3rd_num
            re2nd_name=re3rd_name
            re3rd_num=temp
            re3rd_name=tempname
        if re2nd_num<re1st_num:#적은1순위
            temp=re1st_num
            tempname=re1st_name
            re1st_num=re2nd_num
            re1st_name=re2nd_name
            re2nd_num=temp
            re2nd_name=tempname
print('')
print(subway)
print('이용객이 가장 많은 역 순위')
print('1.',st_name,'(',st_num,')')
print('2.',nd_name,'(',nd_num,')')
print('3.',rd_name,'(',rd_num,')')
print('')
print('이용객이 가장 적은 역 순위')
print('1.',re1st_name,'(',re1st_num,')')
print('2.',re2nd_name,'(',re2nd_num,')')
print('3.',re3rd_name,'(',re3rd_num,')')
print('')

-----------------------------------
1.1호선
2.2호선
3.3호선
4,4호선
5.경부선
6.경인선
7.경원선
8.안산선
9.과천선
10.분당선
11.경부선
12.일산선
13.중앙선
14.장항선
15.경의선
16.경춘선
17.수인선
18.경강선
19.5호선
20.6호선
21.7호선
22.8호선
23.9호선
24.공항철도1호선
25.9호선 2~3단계
26.우이신설선
-----------------------------------
이용객 순위를 볼 노선을 선택하십시오: 3

3호선
이용객이 가장 많은 역 순위
1. 고속터미널 ( 2262541 )
2. 양재(서초구청) ( 2063345 )
3. 연신내 ( 1965286 )

이용객이 가장 적은 역 순위
1. 충무로 ( 35 )
2. 학여울 ( 124884 )
3. 지축 ( 208890 )